---
title: "R Notebook"
output: html_notebook
---


# Packages
#--------------------------------------------------------------------------#
```{r, echo=FALSE, message=FALSE, results='hide'}
library(tidyverse)
library(janitor)
library(jsonlite)
library(here)
```

# API Function
#--------------------------------------------------------------------------#

```{r, echo=FALSE, message=FALSE, results='hide'}
# Function for fetching phs dataframes
phs_df_func <- function(id){
  
  # Link templates for simplicity
  phs_url = "https://www.opendata.nhs.scot/api/3/action/datastore_search?resource_id="
  # fetch maximum 999'999 results for simplicity
  limit_url = "&limit=999999"
  
  # construct URL for fetching process
  url_link <- paste0(phs_url, id, limit_url) %>%
    fromJSON()
  
  # construct dataframe from url
  phs_df <-  url_link[["result"]][["records"]] %>% 
    clean_names()
  
  return(phs_df)

}


phs_dictionary_func <- function(id){
  
  # Link templates for simplicity
  phs_url = "https://www.opendata.nhs.scot/api/3/action/datastore_search?resource_id="
  # fetch maximum 999'999 results for simplicity
  limit_url = "&limit=10"
  
  # construct URL for fetching process
  url_link <- paste0(phs_url, id, limit_url) %>%
    fromJSON()
  
  # construct dataframe from url
  phs_dictionary <-  url_link[["result"]][["fields"]] %>% 
    jsonlite::flatten(recursive = TRUE) %>% 
    select(id, info.label, type)
  #    jsonlite::flatten(recursive = TRUE, use.names = TRUE)

  return(phs_dictionary)
}

```


# API Keys
#--------------------------------------------------------------------------#

```{r, echo=FALSE, message=FALSE, results='hide'}

```

# Load in API Dataframe (Backup)
#--------------------------------------------------------------------------#
```{r}

```


```{r, echo=FALSE, message=FALSE, results='hide'}
make_file_names <- function(x) paste0(target_directory,x,".csv")
save_csv <- function(x) write_csv(obj_list[[x]],file_name[[x]])

target_directory <- here("raw_data//")


name_pattern <- grep("backup_",names(.GlobalEnv),value=TRUE)
obj_list     <- do.call("list",mget(name_pattern))
file_name      <- make_file_names(names(obj_list))

for (i in seq_along(names(obj_list))) save_csv(i)

# Create Dataframe List
name_list <- as_tibble(name_pattern) %>% arrange(value)
namelist_path <- paste0(target_directory,"00_Backup_Dataframe_List.csv")

write.csv(name_list, namelist_path, row.names = FALSE)

```