---
title: "Deloitte Productivity Cleaning Script"
output: html_notebook
---
### Library
```{r}
library(tidyverse)
library(janitor)
library(readxl)
library(here)
library(lubridate)
```

### Functions
```{r}
multiplesheets <- function(fname) {
   
  # getting info about all excel sheets
  sheets <- readxl::excel_sheets(fname)
  tibble <- lapply(sheets, function(x) readxl::read_excel(fname, sheet = x))
  data_frame <- lapply(tibble, as.data.frame)
    
  # assigning names to data frames
  names(data_frame) <- sheets
    
  # print data frame
  print(data_frame)
}
  
# specifying the path name
```

# Meta Data for Productivity Estimates: UK
```{r}
# raw - Raw Files
# pro - Productivity
# Hist - Historical

raw_pro_hist <- multiplesheets(here("data/raw_data/uk_labour_productivity_historical.xls"))

raw_pro_regi <- multiplesheets(here("data/raw_data/uk_Labour Productivity - Region by Industry.xls"))

raw_pro_indu <- multiplesheets(here("data/raw_data/uk_Labour Productivity - Industry division.xls"))

raw_pro_area <- multiplesheets(here("data/raw_data/uk_labour productivity - Rural and urban areas.xls"))

raw_pro_educ <- multiplesheets(here("data/raw_data/uk_labour_productivity_education_2019.xlsx"))

raw_pro_tim  <- multiplesheets(here("data/raw_data/uk_GDP Estimates - Time Series.xlsx"))

# <- multiplesheets("data/raw_data/")

# tt <- read.delim2("data/deloitte_data_dictionary_2019.numbers", header = FALSE)

raw_world_euro <- multiplesheets(here("data/raw_data/International Labour Productivity - Europe.xls"))

raw_world_g7 <- multiplesheets(here("data/raw_data/international_labour_productivity_G7_2020.xlsx"))

raw_world_multi <- multiplesheets(here("data/raw_data/OECD_multifactor_productivity.xls"))
```


# Europe UK Data
```{r}
# Europe Output Per Hour
# Table 1: Output per hour by industry, €

clean_world_euro_oph <- raw_world_euro$`Table 1` %>% 
  na.omit() %>% 
  row_to_names(row_number = 1) %>% 
  clean_names()

# Table 2: Labour Productivity Growth by industry 2014-16, %
clean_world_euro_growth <- raw_world_euro$`Table 2` %>% 
  na.omit() %>% 
  row_to_names(row_number = 1) %>% 
  clean_names()

```


# Time Series
```{r}
clean_pro_time_year <- raw_pro_tim$data %>% 
  clean_names() %>% 
  filter(!grepl(' Q+[0-9]', title))

clean_pro_time_quart <- raw_pro_tim$data %>% 
  clean_names() %>% 
  filter(!grepl('^\\d{4}$', title))
```


```{r}
clean_world_multi <- as.data.frame(raw_world_multi$DP_LIVE_25012019175641197) %>% 
  clean_names() %>% 
  select(-flag_codes)
```

# G7, whole economy, current price (CP) in GBP
# G7 - Output per hours Productivity
```{r}
# Annual output per hour worked 
g7_prod <- raw_world_g7$Table_9 %>% 
  na.omit() %>% 
  row_to_names(row_number = 1) %>% 
  clean_names() %>% 
  pivot_longer(!year, names_to = "country", values_to = "productivity") %>% 
  mutate(productivity = round(as.numeric(productivity), digits = 2))

g7_prod_avg <- g7_prod %>% 
  group_by(year) %>% 
  summarise(productivity = round(mean(productivity), digits = 2))

g7_prod %>% 
  filter(country == "uk") %>% 
  ggplot()+
  aes(x = year, y = productivity, group = country, colour = country)+
  geom_point()+
  geom_line()+
  geom_line(aes(x = g7_prod_avg$year, y = g7_prod_avg$productivity), linetype = 2)+
  labs(title = "Productivity in G7 Countries")+
  xlab("Year")+
  ylab("Output Per Hour Worked (£)")+
  theme(axis.text.x = element_text(angle = 45))
  # scale_color_manual(values = c("us" = "steelblue", "uk" = "red", "japan" = "green"))
```
# G7 - GDP
```{r}
# GDP
g7_gdp <- raw_world_g7$Table_2 %>% 
  na.omit() %>% 
  row_to_names(row_number = 1) %>% 
  clean_names() %>% 
  mutate(across(c(2:8), as.numeric)) %>% 
  pivot_longer(!year, names_to = "country", values_to = "gdp")

g7_gdp_avg <- g7_gdp %>% 
  filter(country != "uk") %>% 
  group_by(year) %>% 
  summarise(g7_avg = mean(gdp))


g7_gdp %>% 
  filter(country == "uk"  ) %>% 
  ggplot()+
  geom_point(aes(x = year, y = gdp, group = country, colour = country))+
  geom_line(aes(x = year, y = gdp, group = country, colour = country))+
  geom_line(aes(x = g7_gdp_avg$year, y = g7_gdp_avg$g7_avg, group = country, colour = country), linetype = 2)+
  labs(title = "GDP comparison between UK and G7 Countries")+
  xlab("Year")+
  ylab("GDP (in million £)")+
  theme(axis.text.x = element_text(angle = 45))
  # scale_color_manual(values = c("us" = "steelblue", "uk" = "red", "japan" = "green"))
    
```

# G7 - Output Per Hour wored growth
```{r}
g7_prod_growth <- raw_world_g7$Table_16%>% 
  na.omit() %>% 
  row_to_names(row_number = 1) %>% 
  clean_names()%>% 
  mutate(across(c(2:8), as.numeric)) %>% 
  pivot_longer(!year, names_to = "country", values_to = "growth_rate")


g7_avg_prod_growth %>% 
  filter(country != "uk") %>% 
  group_by(year) %>% 
  summarise(g7_avg = mean(gdp))
```



