---
title: "D12 Final Project - UK Productivity Analysis"
output:
  html_document:
    toc: yes
    toc_float: yes
    df_print: paged
    pdf_document: default
  word_document:
    toc: yes
---

## Context

### Business intelligence and data-driven decision making

<!-- What insights can the business/organisation gain from your analysis and how will your analysis help the business/organisation make better decisions?  -->

Readers can utilise the analysis to gain an insight into labour productivity performance for difference industries in Scotland. The analysis also provides data-drive suggestions on economic factors that have influence on productivity. 

### Domain knowledge and the business context

<!-- Briefly describe the business/organisation and where your analysis fits within its aims/activity.  -->

The analysis is aimed to aid any business development functions to measure their company's productivity. Readers can use the first analysis on industry productivity as a comparison to their own business, and compare how well the business is performed when compared with Scotland and the UK. The second analysis on productivity factors provide suggestions for further improve the labour productivity.

## Data

### Internal and external data sources

<!-- Briefly describe your data sources and which were internal (provided by the organisation) and external (not sourced from the organisation's data) -->

The original data sources were donated by Deloitte, extracted from [Equifax Ignite Direct](https://www.equifax.co.uk/) data platform. Additional data sources were extracted via [OECD.stat](https://stats.oecd.org/) and [UK National Statistics](https://www.ons.gov.uk/).

### Types of data & Data formats

<!-- What kind of data did you work with? E.g. categorical and numerical data and their sub-types. -->
<!-- What format did your data come in? E.g. all downloaded flat files (CSV) or any data from APIs, scraping etc. -->

Data sources used for this project contained Time series, Date, Doubles, Numeric & Character. The data sources are stored in Excel files (.xls, .csv, .xlsx etc...) with multiple embedded tabs.

### Data quality and bias

<!-- Briefly describe the quality of the data and whether you have any reasons to suggest the data is biased e.g. only data from a specific demographic even though a broader demographic would be of interest to the organisation. -->

The datasets used for this analysis are up-to-date and validated. Sources are extracted from trustworthy authorities.

The analysis provides a high level decoupled analysis of how individual factor affect labour productivity. In reality, there are many confonding factors and interactions that may affect one's productivity, however, they are outwith the consideration of the scope of this project. 


## Ethics

### Ethical issues in data sourcing and extraction

<!-- Do you have any ethical concerns regarding the sourcing and extraction of your data?  -->


The data sources can be found in open source websites and only contain data per country or industry. No individual data set is being used for this analysis with no ethical concerns.

### Ethical implications of business requirements

<!-- Are there any ethical implications of the business requirements? -->

The datasets used for the analysis don't contain any individual personnel or company's information. Therefore it doesn't have any immediate ethical implication and concerns.

## Analysis

### Stages in the data analysis process

<!-- What were the main stages in your data analysis process? -->


Original plan has adapted the generic approach, however, due to the chaotic and inconsistency nature of the datasets, unfamiliar acronyms and lack of economy domain knowledge. The plan was adjusted from one major analysis into 2 small analysis. The original plan and executed plan can be seen below:


#### Original Plan

- Planning

- Research

- Clean & wrangle data

- Process data

- Output results

#### Executed Plan

`Part 01 - Industry Productivity Analysis`

- Research & Gather potential Datasets

- Clean & Wrangle Data

- Analyze Data (modelling)

- Output Results (visualisation)

`Part 02 - Productivity Factor Analysis`

- Research & Gather potential Datasets

- Clean & Wrangle Data

- Analyze Data (hypothesis Test)

- Output Results (visualisation)

### Tools for data analysis



- Data: Excel
- Version Control: Github
- Data Processor: RStudio
- Processing Language: R
- Presentation: Powerpoint


#### R Libraries included:

- tidyverse
- janitor
- readxl
- here
- fable
- lubridate
- slider
- infer

#### Descriptive, diagnostic, predictive and prescriptive analysis

The project's aim is to find out factors that can improve productivity in the UK and analysis which industries are lagging behind in terms of productivity. The analysis required analysing historical data to understand how different factors may affect productivity in the past. Thus, the analysis approach will fall into The Diagnostic Analytics category.